version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  rest-api:
    build: rest-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo